baseurl = "/"
languageCode = "en-us"
title = "Simple and Audacious"
theme = "hugo-theme-casper"
# theme = "LoveIt"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "TODO the description will go here."
  cover = "images/cover.jpg"
  author = "Sumeet Pareek"
  authorlocation = "Boston, USA"
  authorwebsite = "http://simpleandaudacious.com"
  bio= "TODO my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "sumeetpareek"
  twitterName = "TODO"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "TODO"
